import {useEffect,useState} from 'react';
import {api,gameBase} from '@/lib/api';
export default function ClassPicker({onChange}:{onChange:(name:string)=>void}){
 const [reload,setReload]=useState(0);
 const [year,setYear]=useState(''),[classes,setClasses]=useState<string[]>([]),[value,setValue]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[pupils,setPupils]=useState<any[]>([]);
 useEffect(()=>{let alive=true;setLoading(true);setError('');setValue('');onChange('');api({action:'teacher-classes'}).then(data=>{if(!alive)return;setYear(data.schoolyear);setClasses(data.classes);if(!data.classes.length)setError('Er is voor dit schooljaar nog geen klas aan jouw account gekoppeld.');if(data.classes.length===1)setValue(data.classes[0]);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[reload]);
 useEffect(()=>{let alive=true;onChange('');setPupils([]);if(value){setLoading(true);setError('');api({action:'class-roster',className:value}).then(data=>{if(alive){setPupils(data.pupils);onChange(value);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});}return()=>{alive=false;};},[value]);
 return <div className="class-name"><label htmlFor="portal-class">Jouw klas uit de huiswerkapp {year&&<small> · {year}</small>}</label><select id="portal-class" value={value} disabled={loading} onChange={e=>setValue(e.target.value)}><option value="">Kies je klas</option>{classes.map(c=><option key={c}>{c}</option>)}</select>{loading&&<p role="status">Klaslijst laden...</p>}{error&&<div role="alert"><p>{error}</p><a href={new URL('../index.html',gameBase()).href} target="_blank" rel="noreferrer">Aanmelden in de huiswerkapp</a><p>Je dictee blijft hier open. Kom na het aanmelden terug naar dit tabblad.</p></div>}{!loading&&<button type="button" className="text-button" onClick={()=>setReload(n=>n+1)}>Klaslijst opnieuw laden</button>}{pupils.length>0&&<details><summary>{pupils.length} leerlingen gekoppeld</summary><p>{pupils.map(p=>`${p.classNumber}. ${p.firstName}`).join(' · ')}</p></details>}</div>;
}
