'use client';
import type {SpellingEntry} from '@/lib/spelling';
import {useState} from 'react';
import {BookOpen,Check} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter,DialogClose} from '@/components/ui/dialog';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Checkbox} from '@/components/ui/checkbox';
import {Button} from '@/components/ui/button';
import {WORD_GROUPS,WORD_ENTRIES,wordKey,changeSelection} from '@/lib/word-bank';
export default function WordBank({value,onChange}:{value:string,onChange:(value:string,additions:SpellingEntry[])=>void}){
 const [error,setError]=useState('');
 const words=value.split('\n').map(w=>w.trim()).filter(Boolean),selected=new Set(words.map(wordKey));
 function choose(list:string[],select:boolean,groupId:string){const result=changeSelection(value,list,select);setError(result.error);if(!result.error)onChange(result.value,select?list.filter(w=>!selected.has(wordKey(w))).map(w=>({...WORD_ENTRIES[w],groupId})):[]);}
 return <Dialog><DialogTrigger asChild><Button className="bank-open"><BookOpen size={19}/><span><b>Kies uit de woordenbank</b><small>Hele groepen of losse woorden combineren</small></span></Button></DialogTrigger><DialogContent className="word-bank-dialog"><DialogHeader><DialogTitle>Stel je woordenlijst samen</DialogTitle><DialogDescription>Open een groep en kies losse woorden, of voeg de volledige groep toe. Je eigen woorden blijven in de lijst staan.</DialogDescription></DialogHeader><div className="bank-counter" aria-live="polite"><strong>{words.length} / 500 opdrachten om uit te kiezen</strong><span>{WORD_GROUPS.length} groepen · {WORD_GROUPS.reduce((sum,g)=>sum+g.words.length,0)} woord- en zinkeuzes</span></div>{error&&<p role="alert" className="bank-error">{error}</p>}<div className="bank-scroll"><Accordion type="multiple">{WORD_GROUPS.map(group=>{const count=group.words.filter(w=>selected.has(wordKey(w))).length;const all=count===group.words.length;return <AccordionItem key={group.id} value={group.id}><AccordionTrigger className="bank-group-title"><span>{group.title}</span><span className={`group-count ${count?'has-words':''}`}>{count} / {group.words.length}</span></AccordionTrigger><AccordionContent><div className="bank-group-tools"><p>{group.description}</p><Button className="secondary-button" onClick={()=>choose(group.words,!all,group.id)}>{all?'Groep uit lijst halen':'Hele groep kiezen'}</Button></div><div className={`bank-words ${group.id.startsWith('werk-')?'verb-choices':''}`}>{group.words.map(word=><label key={word} className={selected.has(wordKey(word))?'picked':''}><Checkbox checked={selected.has(wordKey(word))} onCheckedChange={checked=>choose([word],checked===true,group.id)}/><span>{WORD_ENTRIES[word]?.sentence?<><b>{WORD_ENTRIES[word].infinitive}</b><small>{WORD_ENTRIES[word].sentence}</small><small>{WORD_ENTRIES[word].tense}</small></>:word}</span></label>)}</div></AccordionContent></AccordionItem>;})}</Accordion></div><DialogFooter className="bank-footer"><p>Kies straks hoeveel opdrachten je dictee telt. Het spel maakt een mix uit je selectie.</p><DialogClose asChild><Button className="primary-button"><Check size={18}/> Klaar met kiezen</Button></DialogClose></DialogFooter></DialogContent></Dialog>;
}
