import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, query, setDoc, where } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyA7KxXMvZ4dzBQDut3CMyWUblLte2tFzoQ",authDomain:"huiswerkapp-a311e.firebaseapp.com",projectId:"huiswerkapp-a311e",storageBucket:"huiswerkapp-a311e.appspot.com",messagingSenderId:"797169941164",appId:"1:797169941164:web:511d9618079f1378d0fd09"};
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const DEFAULT_CLASSES=["K1","K2","K3","1A","2A","3A","4A","5A","6A"],CODES=["z1","z2","z3","z4","p1","p2","p3","p4",...Array.from({length:10},(_,i)=>`b${i+1}`)];
let user=null,role="",klassen=[],leerlingen=[],staat={volgorde:[],registraties:{}},pending=[],leerkrachtNaam="",saveTimer=null,briefjesGeselecteerd=null;

function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function huidigSchooljaar(){const n=new Date(),s=n.getMonth()>=7?n.getFullYear():n.getFullYear()-1;return `${s}-${s+1}`}
function isBreed(){return ["beheerder","secretariaat","directie","zorgcoordinator","zorgleerkracht"].includes(role)}
function leerlingId(s,i=0){return String(s.id||`${s.last||s.lastName||''}_${s.first||s.firstName||''}_${i}`).replaceAll('.', '_')}
function volledigeNaam(s){const l=String(s.last||s.lastName||s.achternaam||"").trim(),f=String(s.first||s.firstName||s.voornaam||"").trim();return(l||f)?`${l}${l&&f?', ':''}${f}`:String(s.naam||s.name||"").trim()}
function schooljaarDatums(){const j=$('schooljaar').value.trim();return{start:`${j.slice(0,4)}-09-01`,eind:`${j.slice(5,9)}-06-30`}}
function hoortBijSchooljaar(s){const d=schooljaarDatums();return(!s.start||s.start<=d.eind)&&(!s.end||s.end>=d.start)}
function alfabetisch(ids){const map=new Map(leerlingen.map((s,i)=>[leerlingId(s,i),s]));return [...ids].sort((a,b)=>volledigeNaam(map.get(a)||{}).localeCompare(volledigeNaam(map.get(b)||{}),'nl'))}
function leerlingMap(){return new Map(leerlingen.map((s,i)=>[leerlingId(s,i),s]))}
function voorEenSeptember(){const start=Number($('schooljaar').value.slice(0,4)),grens=new Date(start,8,2);return new Date()<grens}

async function laadRol(){const s=await getDoc(doc(db,'schoolrollen',user.uid));role=s.exists()?String(s.data().rol||'').toLowerCase():'';if(role==='beheerder'){const sim=localStorage.getItem('lindeSimuleerRol_'+user.uid);if(sim)role=sim}}
async function laadKlassen(){const jaar=$('schooljaar').value.trim();if(isBreed()){const s=await getDocs(collection(db,'schoolbeheer',jaar,'klassen'));klassen=[...new Set([...DEFAULT_CLASSES,...s.docs.map(d=>d.id)])]}else{const email=(user.email||'').toLowerCase(),snaps=await Promise.all([getDocs(query(collection(db,'klasleerkrachten'),where('leerkracht_uids','array-contains',user.uid))),getDocs(query(collection(db,'klasleerkrachten'),where('leerkracht_emails','array-contains',email)))]);const set=new Set();snaps.forEach(s=>s.docs.forEach(d=>{const x=d.data();if(String(x.schooljaar||jaar)===jaar&&x.klas)set.add(String(x.klas).trim())}));klassen=[...set]}klassen.sort((a,b)=>a.localeCompare(b,'nl',{numeric:true}));$('klas').innerHTML=klassen.map(k=>`<option>${esc(k)}</option>`).join('')||'<option value="">Geen klas</option>';await laadKlas()}
async function laadLeerkracht(){leerkrachtNaam='';const jaar=$('schooljaar').value.trim(),klas=$('klas').value;if(!klas)return;const direct=await getDoc(doc(db,'klasleerkrachten',`${jaar}_${klas}`));if(direct.exists()){const d=direct.data(),namen=d.leerkracht_namen||[];leerkrachtNaam=namen.join(' & ')||d.hoofdleerkracht_naam||''}if(!leerkrachtNaam&&!isBreed())leerkrachtNaam=(user.email||'').split('@')[0]}
async function laadKlas(){const jaar=$('schooljaar').value.trim(),klas=$('klas').value;leerlingen=[];staat={volgorde:[],registraties:{}};pending=[];if(!klas){render();return}const snap=await getDoc(doc(db,'schoolbeheer',jaar,'klassen',klas));if(snap.exists()){const d=snap.data();leerlingen=(d.leerlingen||[]).filter(hoortBijSchooljaar);const opgeslagen=d.afwezigheidsattesten||{};staat={volgorde:Array.isArray(opgeslagen.volgorde)?opgeslagen.volgorde:[],registraties:opgeslagen.registraties||{}}}await laadLeerkracht();berekenVolgorde();render()}

function berekenVolgorde(){const ids=leerlingen.map(leerlingId),geldige=new Set(ids);staat.volgorde=staat.volgorde.filter(id=>geldige.has(id));const ontbrekend=ids.filter(id=>!staat.volgorde.includes(id));if(!staat.volgorde.length){staat.volgorde=alfabetisch(ids);pending=[]}else if(voorEenSeptember()){staat.volgorde=alfabetisch([...staat.volgorde,...ontbrekend]);pending=[]}else pending=ontbrekend}
function codeKop(code){return code.charAt(0).toUpperCase()+code.slice(1)}
function renderKop(){const codes=CODES.map(c=>`<th class="code ${c.startsWith('b')&&Number(c.slice(1))<=5?'b-grens':''}">${codeKop(c)}</th>`).join('');$('thead').innerHTML=`<tr><th class="nr"></th><th class="naam">Naam leerling</th>${codes}</tr>`}
function render(){renderKop();const map=leerlingMap(),minimum=Math.max(31,staat.volgorde.length),regels=[];for(let i=0;i<minimum;i++){const id=staat.volgorde[i],s=map.get(id),reg=staat.registraties[id]||{},z=CODES.filter(c=>c.startsWith('z')&&reg[c]).length,b=CODES.filter(c=>c.startsWith('b')&&reg[c]).length;const waarschuwing=[z>=4?'4 Z gebruikt':'',b>=5?'B melden':''].filter(Boolean).join(' · ');regels.push(`<tr><td class="nr">${i+1}</td><td class="naam">${s?`<span class="naamregel"><span>${esc(volledigeNaam(s))}</span>${waarschuwing?`<span class="waarschuwing">${waarschuwing}</span>`:''}</span>`:''}</td>${CODES.map(c=>`<td class="vakje ${reg[c]?'actief':''} ${c.startsWith('b')&&Number(c.slice(1))<=5?'b-grens':''}" ${id?`data-id="${esc(id)}" data-code="${c}"`:''}>${reg[c]?'X':''}</td>`).join('')}</tr>`)}$('tbody').innerHTML=regels.join('');$('tbody').querySelectorAll('[data-id][data-code]').forEach(c=>c.addEventListener('click',()=>toggle(c.dataset.id,c.dataset.code)));$('klasTitel').textContent=`Klas: ${$('klas').value||'—'}`;$('schooljaarTitel').textContent=`Schooljaar ${$('schooljaar').value}`;$('leerkrachtTitel').textContent=`Leerkracht: ${leerkrachtNaam||'—'}`;$('status').textContent=`${leerlingen.length} leerling${leerlingen.length===1?'':'en'} · ${saveTimer?'wijzigingen bewaren…':'bewaard'}`;renderPending();renderBriefjesKeuze()}
function renderPending(){$('pending').classList.toggle('show',pending.length>0);$('pendingLijst').innerHTML=pending.map(id=>{const s=leerlingMap().get(id);return`<div class="pending-kind"><strong>${esc(volledigeNaam(s||{}))}</strong><button class="primary" data-keuze="alpha" data-id="${esc(id)}">Alfabetisch invoegen</button><button class="white" data-keuze="onder" data-id="${esc(id)}">Onderaan toevoegen</button></div>`}).join('');$('pendingLijst').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>voegNieuweToe(b.dataset.id,b.dataset.keuze)))}
async function voegNieuweToe(id,keuze){staat.volgorde=keuze==='alpha'?alfabetisch([...staat.volgorde,id]):[...staat.volgorde,id];pending=pending.filter(x=>x!==id);await bewaar();render()}
function toggle(id,code){staat.registraties[id]||={};staat.registraties[id][code]=!staat.registraties[id][code];if(!staat.registraties[id][code])delete staat.registraties[id][code];clearTimeout(saveTimer);saveTimer=setTimeout(bewaar,450);render()}
async function bewaar(){clearTimeout(saveTimer);saveTimer=null;const ref=doc(db,'schoolbeheer',$('schooljaar').value.trim(),'klassen',$('klas').value);try{await setDoc(ref,{afwezigheidsattesten:{versie:1,volgorde:staat.volgorde,registraties:staat.registraties,bijgewerktOp:new Date().toISOString(),bijgewerktDoor:user.email||user.uid}},{merge:true});render()}catch(e){console.error(e);$('status').textContent='Bewaren mislukt. Controleer je Firebase-toegang.'}}

function renderBriefjesKeuze(){const map=leerlingMap(),ids=staat.volgorde.filter(id=>map.has(id));if(briefjesGeselecteerd===null)briefjesGeselecteerd=new Set(ids);$('briefjesKinderen').innerHTML=ids.map(id=>`<label class="briefjes-kind"><input type="checkbox" data-brief-id="${esc(id)}" ${briefjesGeselecteerd.has(id)?'checked':''}><span>${esc(volledigeNaam(map.get(id)))}</span></label>`).join('');$('briefjesKinderen').querySelectorAll('input[data-brief-id]').forEach(v=>v.addEventListener('change',()=>{v.checked?briefjesGeselecteerd.add(v.dataset.briefId):briefjesGeselecteerd.delete(v.dataset.briefId)}))}
function briefjeHtml(naam,klas,voorinvullen){return `<article class="ziektebriefje"><div class="briefje-kop"><img src="afbeeldingen/schoollogo.png" alt="Logo De Linde"><strong>Z1 - Z2 - Z3 - Z4</strong></div><div class="briefje-titel">AFWEZIGHEID DOOR ZIEKTE</div><div class="briefje-regel"><span>Naam:</span><span class="invullijn">${voorinvullen?esc(naam):''}</span><span>Klas:</span><span class="invullijn">${voorinvullen?esc(klas):''}</span></div><div class="briefje-regel enkel"><span>Was afwezig op:</span><span class="invullijn"></span></div><div class="briefje-regel enkel"><span>Reden:</span><span class="invullijn"></span></div><div class="handtekening-lijn"></div><div class="handtekening">HANDTEKENING OUDERS/VERANTWOORDELIJKE</div><div class="briefje-noot">N.B.: Bij afwezigheid van meer dan 3 opeenvolgende kalenderdagen is een doktersattest vereist.</div></article>`}
function maakBriefjesAfdruk(){const map=leerlingMap(),ids=staat.volgorde.filter(id=>briefjesGeselecteerd.has(id)&&map.has(id));if(!ids.length){alert('Kies eerst minstens één leerling.');return}const voorinvullen=$('briefjesVoorinvullen').checked,klas=$('klas').value;$('briefjesPrint').innerHTML=ids.map(id=>{const naam=volledigeNaam(map.get(id)),briefje=briefjeHtml(naam,klas,voorinvullen);return `<section class="briefjes-pagina">${briefje.repeat(4)}</section>`}).join('');document.body.classList.add('briefjes-print');window.print()}

$('schooljaar').value=huidigSchooljaar();$('klas').addEventListener('change',()=>{briefjesGeselecteerd=null;laadKlas()});$('schooljaar').addEventListener('change',()=>{briefjesGeselecteerd=null;laadKlassen()});$('herladen').addEventListener('click',laadKlas);$('print').addEventListener('click',()=>{document.body.classList.remove('briefjes-print');window.print()});$('briefjesOpen').addEventListener('click',()=>{$('briefjesPaneel').classList.toggle('show');renderBriefjesKeuze()});$('briefjesAlles').addEventListener('click',()=>{briefjesGeselecteerd=new Set(staat.volgorde);renderBriefjesKeuze()});$('briefjesGeen').addEventListener('click',()=>{briefjesGeselecteerd=new Set();$('briefjesKinderen').querySelectorAll('input').forEach(v=>v.checked=false)});$('briefjesAfdrukken').addEventListener('click',maakBriefjesAfdruk);window.addEventListener('afterprint',()=>document.body.classList.remove('briefjes-print'));
onAuthStateChanged(auth,async u=>{if(!u){location.href='index.html';return}user=u;try{await laadRol();await laadKlassen()}catch(e){console.error(e);$('status').textContent='Laden mislukt: '+e.message}});
