(function(){
  "use strict";
  const encoder=new TextEncoder();let crcTable=null;
  function xml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;")}
  function crc32(bytes){if(!crcTable){crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}}let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
  function u16(n){return new Uint8Array([n&255,(n>>>8)&255])}function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
  function samen(...delen){const lengte=delen.reduce((n,x)=>n+x.length,0),uit=new Uint8Array(lengte);let p=0;delen.forEach(x=>{uit.set(x,p);p+=x.length});return uit}
  function zipBestanden(bestanden){const lokaal=[],centraal=[];let offset=0;for(const [naam,tekst] of Object.entries(bestanden)){const n=encoder.encode(naam),d=encoder.encode(tekst),crc=crc32(d),h=samen(u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),n);lokaal.push(h,d);centraal.push(samen(u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),n));offset+=h.length+d.length}const c=samen(...centraal),l=samen(...lokaal),e=samen(u32(0x06054b50),u16(0),u16(0),u16(centraal.length),u16(centraal.length),u32(c.length),u32(l.length),u16(0));return new Blob([l,c,e],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"})}
  function run(tekst,vet=false,grootte=10){return `<w:r><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>${vet?"<w:b/>":""}<w:sz w:val="${grootte*2}"/><w:szCs w:val="${grootte*2}"/></w:rPr><w:t xml:space="preserve">${xml(tekst)}</w:t></w:r>`}
  function cel(tekst,breedte,opties={}){const jc=opties.uitlijning||"left",marge=opties.marge??55,dikkeBovenlijn=opties.dikkeBovenlijn?'<w:tcBorders><w:top w:val="single" w:sz="20" w:space="0" w:color="000000"/></w:tcBorders>':"";return `<w:tc><w:tcPr><w:tcW w:w="${breedte}" w:type="dxa"/>${dikkeBovenlijn}<w:vAlign w:val="center"/><w:tcMar><w:top w:w="25" w:type="dxa"/><w:left w:w="${marge}" w:type="dxa"/><w:bottom w:w="25" w:type="dxa"/><w:right w:w="${marge}" w:type="dxa"/></w:tcMar></w:tcPr><w:p><w:pPr><w:spacing w:before="0" w:after="0"/><w:jc w:val="${jc}"/></w:pPr>${tekst!==""?run(tekst,!!opties.vet,opties.grootte||9):""}</w:p></w:tc>`}
  function rij(cellen,hoogte,exact=true){return `<w:tr><w:trPr><w:cantSplit/><w:trHeight w:hRule="${exact?"exact":"atLeast"}" w:val="${hoogte}"/></w:trPr>${cellen}</w:tr>`}
  function kopRegel(klas,leerkracht,schooljaar){return `<w:tbl><w:tblPr><w:tblW w:w="10100" w:type="dxa"/><w:tblBorders><w:top w:val="nil"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders><w:tblLayout w:type="fixed"/></w:tblPr><w:tblGrid><w:gridCol w:w="6600"/><w:gridCol w:w="3500"/></w:tblGrid>${rij(cel(`Klas: ${klas}${leerkracht?` (${leerkracht})`:""}`,6600,{grootte:12})+cel(`Schooljaar ${schooljaar}`,3500,{grootte:12,uitlijning:"right"}),380,false)}</w:tbl>`}
  function puntenTabel(leerlingen){const breedtes=[600,2700,756,756,756,756,756,756,756,756,756],totaalRijen=Math.max(22,leerlingen.length),leerlingHoogte=454;let regels="";
    regels+=rij(breedtes.map(w=>cel("",w)).join(""),1900);
    regels+=rij(breedtes.map(w=>cel("",w)).join(""),450);
    for(let i=0;i<totaalRijen;i++){const s=leerlingen[i],naam=s?`${s.last||s.lastName||""} ${s.first||s.firstName||""}`.trim():"",lijn=i===0;regels+=rij(cel(s?String(i+1):"",breedtes[0],{uitlijning:"center",grootte:12,dikkeBovenlijn:lijn})+cel(naam,breedtes[1],{grootte:12,dikkeBovenlijn:lijn})+breedtes.slice(2).map(w=>cel("",w,{dikkeBovenlijn:lijn})).join(""),leerlingHoogte)}
    return `<w:tbl><w:tblPr><w:tblW w:w="10104" w:type="dxa"/><w:tblBorders><w:top w:val="single" w:sz="8"/><w:left w:val="single" w:sz="8"/><w:bottom w:val="single" w:sz="8"/><w:right w:val="single" w:sz="8"/><w:insideH w:val="single" w:sz="6"/><w:insideV w:val="single" w:sz="6"/></w:tblBorders><w:tblLayout w:type="fixed"/><w:tblCellMar><w:left w:w="0" w:type="dxa"/><w:right w:w="0" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid>${breedtes.map(w=>`<w:gridCol w:w="${w}"/>`).join("")}</w:tblGrid>${regels}</w:tbl>`}
  function documentXml(opties){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${kopRegel(opties.klas,opties.leerkracht,opties.schooljaar)}<w:p><w:pPr><w:spacing w:before="0" w:after="0" w:line="240" w:lineRule="exact"/></w:pPr></w:p>${puntenTabel(opties.leerlingen)}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="620" w:right="780" w:bottom="620" w:left="780" w:header="0" w:footer="0" w:gutter="0"/></w:sectPr></w:body></w:document>`}
  window.maakKlaslijstWord=function(opties){if(!opties?.leerlingen?.length)throw new Error("Geen actieve leerlingen gevonden.");const bestanden={"[Content_Types].xml":'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>',"_rels/.rels":'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',"word/_rels/document.xml.rels":'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>',"word/document.xml":documentXml(opties)},url=URL.createObjectURL(zipBestanden(bestanden)),a=document.createElement("a");a.href=url;a.download=`klaslijst_${String(opties.klas).replace(/[^a-z0-9_-]+/gi,"_")}_${opties.schooljaar}.docx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
})();
