import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, query, where } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyA7KxXMvZ4dzBQDut3CMyWUblLte2tFzoQ",authDomain:"huiswerkapp-a311e.firebaseapp.com",projectId:"huiswerkapp-a311e",storageBucket:"huiswerkapp-a311e.appspot.com",messagingSenderId:"797169941164",appId:"1:797169941164:web:511d9618079f1378d0fd09"};
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id),DEFAULT_CLASSES=["K1","K2","K3","1A","2A","3A","4A","5A","6A"];
let user=null,role="",leerlingen=[];
function huidigSchooljaar(){const n=new Date(),s=n.getMonth()>=7?n.getFullYear():n.getFullYear()-1;return `${s}-${s+1}`}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function xml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;")}
function roepnaam(s){const officieel=String(s.first||s.firstName||s.voornaam||"").trim();return String(s.roepnaam||s.roepNaam||s.callingName||officieel||"").trim()||String(s.naam||s.name||"").trim().split(/[, ]+/).filter(Boolean).at(-1)||""}
function achternaam(s){const direct=String(s.last||s.lastName||s.achternaam||"").trim();if(direct)return direct;const volledig=String(s.naam||s.name||"").trim();if(!volledig)return "";return volledig.includes(",")?volledig.split(",")[0].trim():volledig.split(/\s+/).slice(1).join(" ").trim()}
function naamSorteersleutel(s){return `${achternaam(s)}${roepnaam(s)}`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/gi,"").toLocaleLowerCase("nl")}
function vergelijk(a,b){return naamSorteersleutel(a).localeCompare(naamSorteersleutel(b),"nl",{sensitivity:"base"})}
function actief(s){const jaar=$("schooljaar").value.trim(),begin=`${jaar.slice(0,4)}-09-01`,einde=`${jaar.slice(5,9)}-06-30`,n=new Date(),vandaag=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,"0")}-${String(n.getDate()).padStart(2,"0")}`,datum=vandaag<begin?begin:vandaag>einde?einde:vandaag;return(!s.start||s.start<=datum)&&(!s.end||s.end>=datum)}
function vergelijkKlassen(a,b){const sleutel=v=>{const s=String(v||"").toUpperCase(),k=s.match(/^K(\d+)(.*)$/),l=s.match(/^(\d+)(.*)$/);return k?[0,+k[1],k[2]]:l?[1,+l[1],l[2]]:[2,999,s]};const x=sleutel(a),y=sleutel(b);return x[0]-y[0]||x[1]-y[1]||x[2].localeCompare(y[2],"nl")}
function isBreed(){return ["beheerder","directie","zorgcoordinator","zorgleerkracht"].includes(role)}
function bladIndeling(){const rijen=Math.max(8,Math.ceil(leerlingen.length/3)),totaal=rijen*3,items=Array.from({length:totaal},(_,i)=>{const leerling=leerlingen[i];return leerling?{nummer:i+1,naam:roepnaam(leerling)}:{nummer:"",naam:""}});return{rijen,items}}
function afdrukNaam(s){return `${achternaam(s)} ${roepnaam(s)}`.trim()}
function render(){const{rijen,items}=bladIndeling(),preview=$("preview"),invul=$("invulPreview");preview.style.setProperty("--klas-rijen",rijen);preview.innerHTML=[0,rijen,rijen*2].map(start=>`<div class="blok">${items.slice(start,start+rijen).map(x=>`<div class="regel"><div class="nummer">${x.nummer}</div><div class="naam">${esc(x.naam)}</div></div>`).join("")}</div>`).join("");const voorbeeldRijen=Math.max(22,leerlingen.length),legeKop=Array.from({length:22},(_,i)=>`<div class="invul-cel ${i<11?'invul-boven':''}"></div>`).join(""),namen=Array.from({length:voorbeeldRijen},(_,i)=>{const s=leerlingen[i];return `<div class="invul-cel ${i===0?'invul-scheiding':''}">${s?i+1:""}</div><div class="invul-cel ${i===0?'invul-scheiding':''}">${s?esc(afdrukNaam(s)):""}</div>${Array.from({length:9},()=>`<div class="invul-cel ${i===0?'invul-scheiding':''}"></div>`).join("")}`}).join("");invul.innerHTML=`<div class="invul-kop"><span>Klas: ${esc($("klas").value||"-")}</span><span>Schooljaar ${esc($("schooljaar").value)}</span></div><div class="invul-tabel">${legeKop}${namen}</div>`;$("status").textContent=leerlingen.length?`${leerlingen.length} actieve leerlingen · alfabetisch op achternaam · beide Wordbladen staan klaar.`:`Geen actieve leerlingen gevonden in deze klaslijst.`;$("download").disabled=!leerlingen.length;$("downloadInvul").disabled=!leerlingen.length}
async function laadRol(){const s=await getDoc(doc(db,"schoolrollen",user.uid));role=s.exists()?String(s.data().rol||"").toLowerCase():"";if(role==="beheerder"){const sim=localStorage.getItem("lindeSimuleerRol_"+user.uid);if(sim)role=sim}}
async function laadKlassen(){const jaar=$("schooljaar").value.trim();let klassen=[];if(isBreed()){const snap=await getDocs(collection(db,"schoolbeheer",jaar,"klassen"));klassen=[...new Set([...DEFAULT_CLASSES,...snap.docs.map(d=>d.id)])]}else{const email=(user.email||"").toLowerCase(),qs=await Promise.all([getDocs(query(collection(db,"klasleerkrachten"),where("leerkracht_uids","array-contains",user.uid))),getDocs(query(collection(db,"klasleerkrachten"),where("leerkracht_emails","array-contains",email)))]),set=new Set();qs.forEach(q=>q.docs.forEach(d=>{const x=d.data();if(String(x.schooljaar||jaar)===jaar&&x.klas)set.add(String(x.klas).trim())}));klassen=[...set]}klassen.sort(vergelijkKlassen);$("klas").innerHTML=klassen.map(k=>`<option>${esc(k)}</option>`).join("")||'<option value="">Geen klas</option>';await laadLeerlingen()}
async function laadLeerlingen(){leerlingen=[];const klas=$("klas").value,jaar=$("schooljaar").value.trim();if(klas){const snap=await getDoc(doc(db,"schoolbeheer",jaar,"klassen",klas));if(snap.exists())leerlingen=(snap.data().leerlingen||[]).filter(actief).sort(vergelijk)}render()}

const encoder=new TextEncoder();let crcTable=null;
function crc32(bytes){if(!crcTable){crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}}let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function u16(n){return new Uint8Array([n&255,(n>>>8)&255])}function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}function samen(...a){const l=a.reduce((s,x)=>s+x.length,0),o=new Uint8Array(l);let p=0;for(const x of a){o.set(x,p);p+=x.length}return o}
function zipBestanden(bestanden){const lokaal=[],centraal=[];let offset=0;for(const [naam,tekst] of Object.entries(bestanden)){const n=encoder.encode(naam),d=encoder.encode(tekst),crc=crc32(d),h=samen(u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),n);lokaal.push(h,d);centraal.push(samen(u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),n));offset+=h.length+d.length}const c=samen(...centraal),l=samen(...lokaal),e=samen(u32(0x06054b50),u16(0),u16(0),u16(centraal.length),u16(centraal.length),u32(c.length),u32(l.length),u16(0));return new Blob([l,c,e],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"})}
function run(tekst,vet=false,grootte=26){return `<w:r><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>${vet?"<w:b/>":""}<w:sz w:val="${grootte*2}"/><w:szCs w:val="${grootte*2}"/></w:rPr><w:t xml:space="preserve">${xml(tekst)}</w:t></w:r>`}
function cel(tekst,breedte,vet=false,grootte=26){return `<w:tc><w:tcPr><w:tcW w:w="${breedte}" w:type="dxa"/><w:vAlign w:val="center"/><w:tcMar><w:top w:w="35" w:type="dxa"/><w:left w:w="70" w:type="dxa"/><w:bottom w:w="35" w:type="dxa"/><w:right w:w="70" w:type="dxa"/></w:tcMar></w:tcPr><w:p><w:pPr><w:spacing w:before="0" w:after="0"/><w:jc w:val="center"/></w:pPr>${tekst!==""?run(tekst,vet,grootte):""}</w:p></w:tc>`}
function tussenruimte(){return `<w:tc><w:tcPr><w:tcW w:w="615" w:type="dxa"/><w:tcBorders><w:top w:val="nil"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/></w:tcBorders></w:tcPr><w:p><w:pPr><w:spacing w:before="0" w:after="0"/></w:pPr></w:p></w:tc>`}
function tabel(items,rijen){let r="",rijhoogte=Math.floor(9800/rijen),grootte=rijen<=8?26:rijen===9?24:rijen===10?22:Math.max(12,22-(rijen-10));for(let y=0;y<rijen;y++){const pos=[y,y+rijen,y+rijen*2],blokken=pos.map(i=>cel(items[i].nummer,850,true,grootte)+cel(items[i].naam,3950,false,grootte));r+=`<w:tr><w:trPr><w:cantSplit/><w:trHeight w:hRule="exact" w:val="${rijhoogte}"/></w:trPr>${blokken[0]}${tussenruimte()}${blokken[1]}${tussenruimte()}${blokken[2]}</w:tr>`}return `<w:tbl><w:tblPr><w:tblW w:w="15630" w:type="dxa"/><w:tblBorders><w:top w:val="single" w:sz="8"/><w:left w:val="single" w:sz="8"/><w:bottom w:val="single" w:sz="8"/><w:right w:val="single" w:sz="8"/><w:insideH w:val="single" w:sz="8"/><w:insideV w:val="single" w:sz="8"/></w:tblBorders><w:tblLayout w:type="fixed"/><w:tblCellMar><w:left w:w="0" w:type="dxa"/><w:right w:w="0" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid>${[850,3950,615,850,3950,615,850,3950].map(w=>`<w:gridCol w:w="${w}"/>`).join("")}</w:tblGrid>${r}</w:tbl>`}
function documentXml(){const{rijen,items}=bladIndeling();return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${tabel(items,rijen)}<w:sectPr><w:pgSz w:w="16838" w:h="11906" w:orient="landscape"/><w:pgMar w:top="500" w:right="600" w:bottom="500" w:left="600" w:header="0" w:footer="0" w:gutter="0"/></w:sectPr></w:body></w:document>`}
function download(){if(!leerlingen.length)return;const bestanden={"[Content_Types].xml":'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>',"_rels/.rels":'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',"word/_rels/document.xml.rels":'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>',"word/document.xml":documentXml()},url=URL.createObjectURL(zipBestanden(bestanden)),a=document.createElement("a");a.href=url;a.download=`klasnummers_${$("klas").value}_${$("schooljaar").value}.docx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
async function downloadInvulbareKlaslijst(){if(!leerlingen.length)return;const klas=$("klas").value,jaar=$("schooljaar").value;let leerkracht="";try{const snap=await getDoc(doc(db,"klasleerkrachten",`${jaar}_${klas}`));if(snap.exists())leerkracht=(snap.data().leerkracht_namen||[]).filter(Boolean).join(" en ")}catch(e){console.warn("Naam klasleerkracht ophalen mislukt",e)}leerkracht=leerkracht||user?.displayName||String(user?.email||"").split("@")[0]||"";window.maakKlaslijstWord({klas,leerkracht,schooljaar:jaar,leerlingen})}

$("schooljaar").value=huidigSchooljaar();$("schooljaar").addEventListener("change",laadKlassen);$("klas").addEventListener("change",laadLeerlingen);$("download").addEventListener("click",download);$("downloadInvul").addEventListener("click",downloadInvulbareKlaslijst);
onAuthStateChanged(auth,async u=>{if(!u){location.href="index.html";return}user=u;try{await laadRol();await laadKlassen()}catch(e){console.error(e);$("status").textContent="De klaslijst kon niet worden geladen: "+e.message}});
