import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, query, where } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyA7KxXMvZ4dzBQDut3CMyWUblLte2tFzoQ",authDomain:"huiswerkapp-a311e.firebaseapp.com",projectId:"huiswerkapp-a311e",storageBucket:"huiswerkapp-a311e.appspot.com",messagingSenderId:"797169941164",appId:"1:797169941164:web:511d9618079f1378d0fd09"};
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id),DEFAULT_CLASSES=["K1","K2","K3","1A","2A","3A","4A","5A","6A"];
let user=null,role="",klassen=[],leerlingen=[],geselecteerd=new Set();

function huidigSchooljaar(){const n=new Date(),s=n.getMonth()>=7?n.getFullYear():n.getFullYear()-1;return `${s}-${s+1}`}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function xml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;")}
function voornaam(s){const d=String(s.first||s.firstName||s.voornaam||"").trim();if(d)return d;const v=String(s.naam||s.name||"").trim();if(v.includes(","))return v.split(",").slice(1).join(",").trim();return v.split(/\s+/)[0]||""}
function achternaam(s){const d=String(s.last||s.lastName||s.achternaam||"").trim();if(d)return d;const v=String(s.naam||s.name||"").trim();if(v.includes(","))return v.split(",")[0].trim();return v.split(/\s+/).slice(1).join(" ").trim()}
function volledigeNaam(s){return [achternaam(s),voornaam(s)].filter(Boolean).join(" ")}
function leerlingId(s,i){return String(s.id||`${achternaam(s)}_${voornaam(s)}_${i}`)}
function actief(s){const jaar=$('schooljaar').value.trim(),datum=`${jaar.slice(0,4)}-09-15`;return(!s.start||s.start<=datum)&&(!s.end||s.end>=datum)}
function gekozen(){return leerlingen.map((s,i)=>({id:leerlingId(s,i),naam:volledigeNaam(s)})).filter(x=>geselecteerd.has(x.id)&&x.naam)}
function magAlleKlassen(){return role==='zorgleerkracht'}
function magGebruiken(){return role==='zorgleerkracht'||!['secretariaat','directie','zorgcoordinator','beheerder'].includes(role)}

function render(){
  const opties=leerlingen.map((s,i)=>({id:leerlingId(s,i),naam:volledigeNaam(s)})),keuze=gekozen();
  $('namen').innerHTML=opties.map(x=>`<label class="naam"><input type="checkbox" data-id="${esc(x.id)}" ${geselecteerd.has(x.id)?'checked':''}><span>${esc(x.naam)}</span></label>`).join('');
  $('namen').querySelectorAll('input[data-id]').forEach(v=>v.addEventListener('change',()=>{v.checked?geselecteerd.add(v.dataset.id):geselecteerd.delete(v.dataset.id);render()}));
  $('downloadRapport').disabled=$('downloadToonmap').disabled=!keuze.length;
  $('status').textContent=leerlingen.length?`${keuze.length} van ${leerlingen.length} actieve leerlingen geselecteerd in ${$('klas').value}.`:'Geen actieve leerlingen gevonden in deze klaslijst.';
  $('bladBadge').textContent=`${keuze.length} ${keuze.length===1?'blad':'bladen'}`;
  $('voorbeeldTitel').textContent=$('voorbeeldType').value;$('voorbeeldJaar').textContent=$('schooljaar').value;$('voorbeeldNaam').textContent=`Naam: ${keuze[0]?.naam||''}`;
}
async function laadRol(){const s=await getDoc(doc(db,'schoolrollen',user.uid));role=s.exists()?String(s.data().rol||'').toLowerCase():'';if(role==='beheerder')role=localStorage.getItem('lindeSimuleerRol_'+user.uid)||'beheerder';if(!magGebruiken())throw new Error('Deze functie is alleen beschikbaar voor klasleerkrachten en zorgleerkrachten.')}
async function laadKlassen(){
  const jaar=$('schooljaar').value.trim();
  if(magAlleKlassen()){const snap=await getDocs(collection(db,'schoolbeheer',jaar,'klassen'));klassen=[...new Set([...DEFAULT_CLASSES,...snap.docs.map(d=>d.id)])]}
  else{const email=(user.email||'').toLowerCase(),qs=await Promise.all([getDocs(query(collection(db,'klasleerkrachten'),where('leerkracht_uids','array-contains',user.uid))),getDocs(query(collection(db,'klasleerkrachten'),where('leerkracht_emails','array-contains',email)))]);const set=new Set();qs.forEach(q=>q.docs.forEach(d=>{const x=d.data();if(String(x.schooljaar||jaar)===jaar&&x.klas)set.add(String(x.klas).trim())}));klassen=[...set]}
  klassen.sort((a,b)=>a.localeCompare(b,'nl',{numeric:true}));$('klas').innerHTML=klassen.map(k=>`<option>${esc(k)}</option>`).join('')||'<option value="">Geen klas gekoppeld</option>';await laadLeerlingen();
}
async function laadLeerlingen(){const klas=$('klas').value,jaar=$('schooljaar').value.trim();leerlingen=[];if(klas){const s=await getDoc(doc(db,'schoolbeheer',jaar,'klassen',klas));if(s.exists())leerlingen=(s.data().leerlingen||[]).filter(actief).sort((a,b)=>volledigeNaam(a).localeCompare(volledigeNaam(b),'nl'))}geselecteerd=new Set(leerlingen.map(leerlingId));render()}

const encoder=new TextEncoder();let crcTable=null;
function crc32(bytes){if(!crcTable){crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}}let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function u16(n){return new Uint8Array([n&255,(n>>>8)&255])}function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}function samen(...a){const l=a.reduce((s,x)=>s+x.length,0),o=new Uint8Array(l);let p=0;for(const x of a){o.set(x,p);p+=x.length}return o}
function zipBestanden(bestanden){const lokaal=[],centraal=[];let offset=0;for(const [naam,data] of Object.entries(bestanden)){const n=encoder.encode(naam),d=typeof data==='string'?encoder.encode(data):data,crc=crc32(d),h=samen(u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),n);lokaal.push(h,d);centraal.push(samen(u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),n));offset+=h.length+d.length}const c=samen(...centraal),l=samen(...lokaal),e=samen(u32(0x06054b50),u16(0),u16(0),u16(centraal.length),u16(centraal.length),u32(c.length),u32(l.length),u16(0));return new Blob([l,c,e],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})}
function run(tekst,grootte){return `<w:r><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:color w:val="3A7C22"/><w:sz w:val="${grootte*2}"/><w:szCs w:val="${grootte*2}"/></w:rPr><w:t xml:space="preserve">${xml(tekst)}</w:t></w:r>`}
function alinea(tekst,grootte,uitlijning='center',voor=0,na=0){return `<w:p><w:pPr><w:spacing w:before="${voor}" w:after="${na}"/><w:jc w:val="${uitlijning}"/></w:pPr>${run(tekst,grootte)}</w:p>`}
function afbeelding(id){return `<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:before="0" w:after="0"/></w:pPr><w:r><w:drawing><wp:inline xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" distT="0" distB="0" distL="0" distR="0"><wp:extent cx="4937760" cy="5133600"/><wp:docPr id="${id}" name="Schoollogo"/><wp:cNvGraphicFramePr><a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" noChangeAspect="1"/></wp:cNvGraphicFramePr><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="${id}" name="Schoollogo"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rId2" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="4937760" cy="5133600"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`}
function pagina(type,jaar,naam,index){const einde=alinea(`Naam: ${naam}`,28,'left',960,0);return alinea(type,110,'center',0,0)+alinea(jaar,36,'center',120,420)+afbeelding(index+1)+einde}
function documentXml(type,namen){const jaar=$('schooljaar').value.trim(),inhoud=namen.map((x,i)=>pagina(type,jaar,x.naam,i)+(i<namen.length-1?'<w:p><w:r><w:br w:type="page"/></w:r></w:p>':'')).join('');return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>${inhoud}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="170" w:footer="708" w:gutter="0"/></w:sectPr></w:body></w:document>`}
async function maakDocx(type){const namen=gekozen();if(!namen.length)return;const logo=new Uint8Array(await (await fetch('afbeeldingen/schoollogo.png')).arrayBuffer()),bestanden={
  '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>',
  '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
  'word/_rels/document.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/schoollogo.png"/></Relationships>',
  'word/styles.xml':'<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="0"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style></w:styles>',
  'word/document.xml':documentXml(type,namen),'word/media/schoollogo.png':logo};
  const url=URL.createObjectURL(zipBestanden(bestanden)),a=document.createElement('a');a.href=url;a.download=`voorbladen_${type.toLowerCase()}_${$('klas').value}_${$('schooljaar').value}.docx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);
}

$('schooljaar').value=huidigSchooljaar();$('schooljaar').addEventListener('change',laadKlassen);$('klas').addEventListener('change',laadLeerlingen);$('voorbeeldType').addEventListener('change',render);$('selecteerAlles').addEventListener('click',()=>{geselecteerd=new Set(leerlingen.map(leerlingId));render()});$('selecteerGeen').addEventListener('click',()=>{geselecteerd.clear();render()});$('downloadRapport').addEventListener('click',()=>maakDocx('Rapport'));$('downloadToonmap').addEventListener('click',()=>maakDocx('Toonmap'));
onAuthStateChanged(auth,async u=>{if(!u){location.href='index.html';return}user=u;try{await laadRol();await laadKlassen()}catch(e){console.error(e);$('status').textContent=e.message;$('klas').innerHTML='<option value="">Geen toegang</option>'}});
