import {spellingCorrect} from '@/lib/spelling';
import {database} from '@/lib/database';
import {questions,validSettings,publicQuestion} from '@/lib/race';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const fail=(msg:string,status=400)=>json({error:msg},status);
const codePattern=/^[A-Z2-9]{6}$/;
async function roomFor(code:string){if(!codePattern.test(code))return null;return database().prepare('SELECT * FROM rooms WHERE code=? AND created>?').bind(code,Date.now()-86400000).first<any>();}
export async function GET(req:Request){try{const u=new URL(req.url),code=(u.searchParams.get('code')||'').toUpperCase();const room=await roomFor(code);if(!room)return fail('Deze race bestaat niet meer. Vraag de nieuwe code aan je juf of meester.',404);
 const db=database(); const all=await db.prepare('SELECT id,name,score,finished,round,corrected FROM players WHERE room=? ORDER BY id').bind(code).all();
 let me=null;const token=u.searchParams.get('token');if(token){const p=await db.prepare('SELECT * FROM players WHERE room=? AND token=?').bind(code,token).first<any>();if(p){const qs=JSON.parse(room.questions);me={id:p.id,name:p.name,score:p.score,mistakes:p.mistakes,finished:p.finished,round:p.round,corrected:p.corrected,correction:JSON.parse(room.settings).kind==='spelling'&&p.round===room.round&&!p.corrected?qs[room.round]?.word:null,question:room.status==='running'&&Date.now()>=room.started&&p.score<qs.length?publicQuestion(qs[JSON.parse(room.settings).kind==='spelling'?room.round:p.score],JSON.parse(room.settings).kind==='spelling'?room.round:p.score):null};}}
 const entries=JSON.parse(room.settings).entries;const prompt=req.headers.get('x-race-host')===room.host&&JSON.parse(room.settings).kind==='spelling'?entries?.[room.round]||null:null;
 return json({hostPrompt:prompt,code,status:room.status,settings:{...JSON.parse(room.settings),words:[],entries:[]},started:room.started,round:room.round,serverNow:Date.now(),players:all.results,me});
 }catch(e){console.error(e);return fail('De verbinding lukt even niet. Probeer opnieuw.',503);}}
export async function POST(req:Request){try{
 const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return fail('Ongeldige aanvraag.',403);
 const b=await req.json() as any,db=database();
 if(b.action==='create'){if(!validSettings(b.settings))return fail('Kies tafels, een soort oefening en het aantal vragen.');const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),v=>alphabet[v%alphabet.length]).join('');const host=crypto.randomUUID();await db.prepare('INSERT INTO rooms(code,host,settings,questions,created) VALUES(?,?,?,?,?)').bind(code,host,JSON.stringify(b.settings),JSON.stringify(questions(b.settings)),Date.now()).run();return json({code,host});}
 const code=String(b.code||'').toUpperCase(),room=await roomFor(code);if(!room)return fail('Race niet gevonden of verlopen.',404);
 if(b.action==='join'){if(room.status!=='waiting')return fail('Deze race is al gestart. Wacht op de volgende ronde.');const name=String(b.name||'').trim().slice(0,18);if(!name)return fail('Vul je voornaam in.');const token=crypto.randomUUID();const result=await db.prepare("INSERT INTO players(room,token,name) SELECT ?,?,? WHERE (SELECT COUNT(*) FROM players WHERE room=?)<32 AND (SELECT status FROM rooms WHERE code=?)='waiting'").bind(code,token,name,code,code).run();if(!result.meta.changes)return fail('De race is vol of al gestart.');return json({token,id:result.meta.last_row_id});}
 if(['start','end','next'].includes(b.action)){if(b.host!==room.host)return fail('Alleen de leerkracht kan dit doen.',403);if(b.action==='start'){if(room.status!=='waiting')return fail('Deze race is al gestart.');const p=await db.prepare('SELECT COUNT(*) AS n FROM players WHERE room=?').bind(code).first<any>();if(!p.n)return fail('Laat eerst een kind deelnemen.');await db.prepare("UPDATE rooms SET status='running',started=? WHERE code=? AND status='waiting'").bind(Date.now()+4000,code).run();}else if(b.action==='next'){if(JSON.parse(room.settings).kind!=='spelling'||room.status!=='running')return fail('Deze ronde kan niet verder.');const remaining=await db.prepare('SELECT COUNT(*) AS n FROM players WHERE room=? AND (round<? OR corrected=0)').bind(code,room.round).first<any>();if(remaining.n)return fail('Wacht tot iedereen het woord heeft afgerond.');const total=JSON.parse(room.questions).length;if(room.round+1>=total)await db.prepare("UPDATE rooms SET status='ended' WHERE code=?").bind(code).run();else await db.prepare('UPDATE rooms SET round=round+1 WHERE code=? AND round=?').bind(code,room.round).run();}else await db.prepare("UPDATE rooms SET status='ended' WHERE code=?").bind(code).run();return json({ok:true});}
 if(b.action==='answer'){if(room.status!=='running'||Date.now()<room.started)return fail('De race is nog niet gestart of is afgelopen.');const p=await db.prepare('SELECT * FROM players WHERE room=? AND token=?').bind(code,String(b.token||'')).first<any>();if(!p)return fail('Meld je opnieuw aan.',403);const qs=JSON.parse(room.questions);if(JSON.parse(room.settings).kind==='spelling'){if(b.index!==room.round)return json({stale:true});if(p.round===room.round&&p.corrected)return json({correct:true,done:true});if(typeof b.answer!=='string'||!b.answer.trim()||b.answer.length>70)return fail('Typ eerst het woord.');const correct=spellingCorrect(b.answer,qs[room.round].word,qs[room.round].caseSensitive);if(correct)await db.prepare('UPDATE players SET score=score+1,round=?,corrected=1,finished=? WHERE id=? AND (round<? OR corrected=0)').bind(room.round,room.round+1===qs.length?Date.now():0,p.id,room.round).run();else await db.prepare('UPDATE players SET round=?,corrected=0,mistakes=mistakes+? WHERE id=? AND (round<? OR corrected=0)').bind(room.round,p.round===room.round?0:1,p.id,room.round).run();return json({correct});}if(p.score>=qs.length)return json({correct:true,finished:true});if(b.index!==p.score)return json({stale:true});if(!Number.isInteger(b.answer)||b.answer<0||b.answer>100)return fail('Vul een getal van 0 tot 100 in.');const correct=b.answer===qs[p.score].answer;if(correct){await db.prepare('UPDATE players SET score=score+1,finished=? WHERE id=? AND score=?').bind(p.score+1===qs.length?Date.now():0,p.id,p.score).run();if(p.score+1===qs.length)await db.prepare("UPDATE rooms SET status='ended' WHERE code=? AND status='running' AND NOT EXISTS (SELECT 1 FROM players WHERE room=? AND finished=0)").bind(code,code).run();}else await db.prepare('UPDATE players SET mistakes=mistakes+1 WHERE id=? AND score=?').bind(p.id,p.score).run();return json({correct});}
 return fail('Onbekende actie.');
 }catch(e){console.error(e);return fail('Opslaan lukte even niet. Probeer opnieuw.',503);}}
