import {plainEntry,validEntry,type SpellingEntry} from './spelling';
export type Kind='tables'|'split'|'ten'|'twenty'|'spelling';
export type Settings={kind:Kind,words:string[],entries?:SpellingEntry[],tables:number[],multiply:boolean,divide:boolean,add:boolean,subtract:boolean,bridge:boolean,maxSplit:number,count:number};
export type Question={text:string,answer:number,type?:'split'|'spelling',word?:string,article?:'de'|'het',sentence?:string,infinitive?:string,tense?:string,caseSensitive?:boolean,total?:number,part?:number};
export function questions(s:Settings):Question[]{
 if(s.kind==='spelling')return (s.entries||s.words.map(plainEntry)).map(e=>({text:e.sentence?'Vul het werkwoord in':'Luister en typ het woord',type:'spelling',word:e.answer,article:e.article,sentence:e.sentence,infinitive:e.infinitive,tense:e.tense,caseSensitive:e.caseSensitive,answer:0}));
 const pool:Question[]=[];
 if(s.kind==='tables'){for(const t of s.tables)for(let n=1;n<=10;n++){if(s.multiply)pool.push({text:`${n} × ${t}`,answer:n*t});if(s.divide)pool.push({text:`${n*t} : ${t}`,answer:n});}}
 else if(s.kind==='split'){for(let total=2;total<=s.maxSplit;total++)for(let part=0;part<=total;part++)pool.push({text:`Splits ${total}`,answer:total-part,type:'split',total,part});}
 else {const max=s.kind==='ten'?10:20;for(let a=0;a<=max;a++)for(let b=0;b<=max;b++){if(s.add&&a+b<=max&&(s.kind!=='twenty'||s.bridge||a%10+b%10<=10||a%10===0||b%10===0))pool.push({text:`${a} + ${b}`,answer:a+b});if(s.subtract&&a>=b&&(s.kind!=='twenty'||s.bridge||a%10>=b%10||a%10===0||b%10===0))pool.push({text:`${a} − ${b}`,answer:a-b});}}
 const result:Question[]=[];while(result.length<s.count){const batch=[...pool];for(let i=batch.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[batch[i],batch[j]]=[batch[j],batch[i]];}result.push(...batch);}return result.slice(0,s.count);
}
export function validSettings(s:any):s is Settings{if(s?.kind==='spelling')return Array.isArray(s.words)&&s.words.length>=1&&s.words.length<=40&&s.words.every((w:any)=>typeof w==='string'&&w.trim().length>0&&w.trim().length<=200)&&s.count===s.words.length&&(!s.entries||(Array.isArray(s.entries)&&s.entries.length===s.words.length&&s.entries.every((e:any,i:number)=>validEntry(e)&&e.label===s.words[i])));return s&&['tables','split','ten','twenty'].includes(s.kind)&&[10,15,20,30,40].includes(s.count)&&(s.kind==='tables'?Array.isArray(s.tables)&&s.tables.length>0&&s.tables.length<=10&&s.tables.every((t:any)=>Number.isInteger(t)&&t>=1&&t<=10)&&typeof s.multiply==='boolean'&&typeof s.divide==='boolean'&&(s.multiply||s.divide):s.kind==='split'?Number.isInteger(s.maxSplit)&&s.maxSplit>=2&&s.maxSplit<=10:typeof s.add==='boolean'&&typeof s.subtract==='boolean'&&(s.add||s.subtract)&&typeof s.bridge==='boolean');}
export function publicQuestion(q:Question,index:number){return {text:q.text,index,...(q.type==='spelling'?{type:q.type,article:q.article,sentence:q.sentence,infinitive:q.infinitive,tense:q.tense,caseSensitive:q.caseSensitive}:{}),...(q.type==='split'?{type:q.type,total:q.total,part:q.part}:{})};}
